<!doctypehtml><html lang=id><meta charset=UTF-8><meta content="width=device-width,initial-scale=1"name=viewport><title>Simpan Content</title><link href=assets/images/logo2.png rel="shortcut icon"type=image/x-icon><link href=styles.css rel=stylesheet><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap"rel=stylesheet><link href=img/about.png rel=icon><style>body{font-family:Poppins,sans-serif;background:linear-gradient(to right,#74ebd5,#acb6e5);margin:0;padding:0;display:flex;justify-content:center;align-items:center;height:100vh}.container{background:#fff;padding:40px;border-radius:15px;box-shadow:0 10px 30px rgba(0,0,0,.1);max-width:500px;width:100%;text-align:center}.logo{width:100px;height:100px;background:url(logo.png) no-repeat center center;background-size:cover;border-radius:50%;margin:0 auto 20px auto}h1{font-size:30px;margin-bottom:20px;color:#333}p{font-size:18px;color:#666;margin-bottom:20px}textarea{width:100%;height:150px;padding:15px;margin-bottom:20px;border:1px solid #ddd;border-radius:10px;resize:vertical;font-size:16px;font-family:Poppins,sans-serif}button{width:100%;padding:15px;background-color:#ff6f61;border:none;color:#fff;font-size:18px;cursor:pointer;border-radius:10px;transition:background-color .3s,transform .3s}button:hover{background-color:#ff4a3c;transform:translateY(-3px)}.message{text-align:center;margin-top:20px;font-size:16px;color:#28a745}.snowflake{position:fixed;top:-10px;z-index:1000;color:#fff;font-size:1.2em;pointer-events:none;animation:fall linear infinite}@keyframes fall{0%{transform:translateY(0);opacity:1}100%{transform:translateY(100vh);opacity:0}}</style><div class=container><div class=logo></div><h1>Simpan FransXeagle</h1><p>Masukkan teks yang ingin Anda simpan di bawah ini:<form action=save_paste.php method=POST><label for=title>Judul:</label><br><input id=title name=title required><br><br><label for=content>Konten:</label><br><textarea cols=30 id=content name=content required rows=10></textarea><br><br><input type=submit value="Simpan Paste"></form><?php

        if (isset($_GET['message'])) {

            echo '<div class="message">' . htmlspecialchars($_GET['message']) . '</div>';
        }

        ?></div>
    <script>
        let snowflakeCount=0;const maxSnowflakes=20;function createSnowflake(){if(snowflakeCount>=20)return;const e=document.createElement("div");e.classList.add("snowflake"),e.innerHTML="❄️",e.style.left=Math.random()*window.innerWidth+"px",e.style.fontSize=10*Math.random()+10+"px",e.style.animationDuration=5*Math.random()+5+"s",e.style.animationDelay=3*Math.random()+"s",document.body.appendChild(e),snowflakeCount++,e.addEventListener("animationend",(()=>{e.remove(),snowflakeCount--}))}setInterval(createSnowflake,1e3),document.addEventListener("DOMContentLoaded",(()=>{const e=document.body;let t=0,n=0,o=0;document.addEventListener("mousemove",(a=>{isThrottled||(t=a.clientX,n=a.clientY,Math.random()<.15&&function(t,n){const a=Date.now();if(a-o<100)return;o=a;const s=document.createElement("div");s.className="mouse-snowflake";const d=3*Math.random()+1;s.style.width=d+"px",s.style.height=d+"px";const l=30*(Math.random()-.5),i=10*(Math.random()-.5);s.style.left=t+l+"px",s.style.top=n+i+"px";const r=2*Math.random()+1;s.style.animation=`mouseFall ${r}s linear forwards`,e.appendChild(s),setTimeout((()=>{s.remove()}),1e3*r)}(t,n),isThrottled=!0,setTimeout((()=>{isThrottled=!1}),50))}))}));
    </script>
</body>



</html>